name: Daily Schedule

on:
  schedule:
    # Runs at minute 30 of every hour from 00:00 to 17:00 UTC
    # This equals 06:00 AM to 11:00 PM IST
    - cron: '30 0-17 * * *'
  # Allows you to manually trigger the script for testing
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Download your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install libraries (requests, selenium, etc.)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. Run your script
      - name: Run Automation
        env:
          XLRI_USERNAME: ${{ secrets.XLRI_USERNAME }}
          XLRI_PASSWORD: ${{ secrets.XLRI_PASSWORD }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py